// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCygSdoITLSOVaPhfX5mk09OoRc8pVE7HA',
    appId: '1:1088949057873:web:3ccfd64b7034d45cc67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    authDomain: 'fx-chat-f14ee.firebaseapp.com',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    measurementId: 'G-9MCWVQR5ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCijxrf0_C0mHAUUCOkee03i9cVmQq0SMg',
    appId: '1:1088949057873:android:6893bf33c65ae511c67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLGbqg4UHAdAxAJocJadJubDG-NtB-yU4',
    appId: '1:1088949057873:ios:c52cdc0b637838f0c67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithGoogleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLGbqg4UHAdAxAJocJadJubDG-NtB-yU4',
    appId: '1:1088949057873:ios:c52cdc0b637838f0c67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterWithGoogleMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCygSdoITLSOVaPhfX5mk09OoRc8pVE7HA',
    appId: '1:1088949057873:web:d90709d8ced20cc0c67b70',
    messagingSenderId: '1088949057873',
    projectId: 'fx-chat-f14ee',
    authDomain: 'fx-chat-f14ee.firebaseapp.com',
    storageBucket: 'fx-chat-f14ee.firebasestorage.app',
    measurementId: 'G-N1B4ZXF19M',
  );

}